/** Declaration file generated by dts-gen */

export function d(...args: any[]): void;

export function dline(char?: any, length?: any): void;

export function e(...args: any[]): void;

export function eline(char?: any, length?: any): void;

export function h(...args: any[]): void;

export function hline(char?: any, length?: any): void;

export function i(...args: any[]): void;

export function iline(char?: any, length?: any): void;

export function line(char?: any, length?: any): void;

export function s(...args: any[]): void;

export function sline(char: any, length: any): void;

export function t(...args: any[]): void;

export function tline(char?: any, length?: any): void;

export function w(...args: any[]): void;

export function wline(char?: any, length?: any): void;

export namespace d {
	const prototype: {};
}

export namespace dline {
	const prototype: {};
}

export namespace e {
	const prototype: {};
}

export namespace eline {
	const prototype: {};
}

export namespace h {
	const prototype: {};
}

export namespace hline {
	const prototype: {};
}

export namespace i {
	const prototype: {};
}

export namespace iline {
	const prototype: {};
}

export namespace line {
	const prototype: {};
}

export namespace s {
	const prototype: {};
}

export namespace sline {
	const prototype: {};
}

export namespace t {
	const prototype: {};
}

export namespace tline {
	const prototype: {};
}

export namespace w {
	const prototype: {};
}

export namespace wline {
	const prototype: {};
}
